version: "3.7"

services:
  advertisement:
    image: advertisement-image
    volumes:
      - .:/advertisement:cached
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    restart: always
    container_name: advertisement-db
    image: postgres:10-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5435:5432